export default {
  ['en-US']: {
    '_settings': {
      rootWidth: '400px',
      numberInputMinWidth: '42px',
      controlWidth: '215px',
    },
    'ui.subtitle': 'Liquid Glass Effect Simulation Tool based on WebGL2',
    'editor.basicSettings': 'Basic Settings',
    'editor.language': 'Language',
    'editor.refThickness': 'Thickness',
    'editor.refFactor': 'Refraction Factor',
    'editor.refDispersion': 'Dispersion Gain',
    'editor.refFresnelRange': 'Fresnel Size',
    'editor.refFresnelHardness': 'Fresnel Hardness',
    'editor.refFresnelFactor': 'Fresnel Intensity',
    'editor.glareRange': 'Glare Size',
    'editor.glareHardness': 'Glare Hardness',
    'editor.glareConvergence': 'Glare Convergence',
    'editor.glareOppositeFactor': 'Glare Opposite Side',
    'editor.glareFactor': 'Glare Intensity',
    'editor.glareAngle': 'Glare Angle',
    'editor.blurRadius': 'Blur Radius',
    'editor.blurMargin': 'Blur Margin',
    'editor.tint': 'Tint',
    'editor.shadowExpand': 'Shadow Expand',
    'editor.shadowFactor': 'Shadow Intensity',
    'editor.shadowPosition': 'Shadow Position',
    'editor.bgType': 'Background',
    'editor.shapeSettings': 'Shape Settings',
    'editor.shapeWidth': 'Width',
    'editor.shapeHeight': 'Height',
    'editor.shapeRadius': 'Radius (%)',
    'editor.shapeRoundness': 'SuperEllipse Factor',
    'editor.showShape1': 'Show 2nd Shape',
    'editor.animationSettings': 'Animation Settings',
    'editor.springSizeFactor': 'Animation Morph',
    'editor.debugSettings': 'Debug',
  },
}
